
#ifndef _LIGHTING_INTERNAL_H_
#define _LIGHTING_INTERNAL_H_

enum wdt_delay {
  WDT_DELAY_16MS,
  WDT_DELAY_32MS,
  WDT_DELAY_64MS,
  WDT_DELAY_128MS,
  WDT_DELAY_250MS,
  WDT_DELAY_500MS,
  WDT_DELAY_1S,
  WDT_DELAY_2S,
  WDT_DELAY_4S,
  WDT_DELAY_8S,
  WDT_DELAY_UNKNOWN
};

#endif /*_LIGHTING_INTERNAL_H_*/
